on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "affan-todolist" #Must be unique in Heroku
        heroku_email: "affanraog11@gmail.com"
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    

